name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      misp_ref:
        description: 'MISP branch or tag to build'
        required: true
        default: 'develop'


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Fetch variables
      run: python3 .github/workflows/docker-version.py ${{ github.event.inputs.misp_ref }}
      id: variables
    -
      name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/mazdafunsunn/misp-nukib-openshift:latest
        build-args: |
          CACHEBUST=${{ steps.variables.outputs.MISP_COMMIT }}
          MISP_VERSION=${{ steps.variables.outputs.MISP_VERSION }}
